Actividad4LenPro3/Models/Estudiante.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Actividad4LenPro3.Models;

public partial class Estudiante
{
    [Key]
    public int Id { get; set; }
    [Required(ErrorMessage ="El nombre es requerido")]
    [StringLength(100)]
    public string NombreCompleto { get; set; } = null!;
    [Required(ErrorMessage = "La matricula es requerido")]
    [StringLength(15, MinimumLength = 6, ErrorMessage ="Debe tener al menos 6 caracteres")]
    public string Matricula { get; set; } = null!;
    [Required(ErrorMessage ="La carrera es requerida")]
    public string Carrera { get; set; } = null!;
    [Required(ErrorMessage ="El correo es requerido")]
    [EmailAddress(ErrorMessage ="El correo es invalido")]
    public string CorreoElectronico { get; set; } = null!;
    [Phone(ErrorMessage ="El telefono es invalido")]
    [MinLength(10, ErrorMessage ="El telefono debe tener minimo 10 caracteres")]
    public string? Telefono { get; set; }
    [Required(ErrorMessage ="La fecha es requerida")]
    [DataType(DataType.Date, ErrorMessage ="La fecha no es valida")]
    public DateOnly FechaNacimiento { get; set; }
    [Required(ErrorMessage ="El genero es requerido")]
    public string Genero { get; set; } = null!;
    [Required(ErrorMessage ="El turno es requerido")]
    public string Turno { get; set; } = null!;
    [Required(ErrorMessage ="El tipo de ingreso es requerido")]
    public string TipoIngreso { get; set; } = null!;
    
    public bool EstaBecado { get; set; }
    //[Range(0, 10, ErrorMessage ="El porcentaje debe ser entre 0 y 10")]
    public int? PorcentajeBeca { get; set; }

    [Required(ErrorMessage ="Los termino son requeridos")]
    public bool TerminoCondicione { get; set; }

    public virtual ICollection<Calificacione> Calificaciones { get; set; } = new List<Calificacione>();
}

Actividad4LenPro3/Controllers/EstudiantesController.cs
using Actividad4LenPro3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Actividad4LenPro3.Controllers
{
    public class EstudiantesController : Controller
    {
        private readonly Actividad4LenPro3Context _context;

        public EstudiantesController(Actividad4LenPro3Context context)
        {
            _context = context;
        }

        
        public IActionResult Index()
        {
            return View("Crear");
        }

        
        [HttpPost]
        public IActionResult Registrar(Estudiante model)
        {
            if (!ModelState.IsValid)
            {
                return View("Crear", model);
            }

            _context.Estudiantes.Add(model);
            var rowCounts = _context.SaveChanges();

            if(rowCounts > 0)
            {
                ViewBag.Mensaje = "Estudiante registrado correctamente!";
            }
            else
            {
                ViewBag.Mensaje = "Algo salio mal al registrar el estudiante";

            }

            return RedirectToAction("Lista");
        }

        
        [HttpGet]
        public IActionResult Lista()
        {
            var estudiantes = _context.Estudiantes.ToList();
            return View(estudiantes);
        }


        [HttpGet]
        public IActionResult Editar(string matricula)
        {
            var estudiante = _context.Estudiantes.FirstOrDefault(e => e.Matricula == matricula);

            if (estudiante == null)
            {
                ViewBag.Mensaje = "El estudiante no existe.";
                return RedirectToAction("Lista");
            }

            return View("Editar", estudiante);
        }



        [HttpPost]
        public IActionResult Editar(Estudiante estudiante)
        {
            if (!ModelState.IsValid)
            {
                return View("Editar", estudiante);
            }

            var estudianteActual = _context.Estudiantes.FirstOrDefault(e => e.Matricula.Equals(estudiante.Matricula));

            if (estudianteActual == null)
            {
                ViewBag.Mensaje = "El estudiante no existe.";
                return RedirectToAction("Lista");
            }

            estudianteActual.NombreCompleto = estudiante.NombreCompleto;
            estudianteActual.Carrera = estudiante.Carrera;
            estudianteActual.CorreoElectronico = estudiante.CorreoElectronico;
            estudianteActual.Telefono = estudiante.Telefono;
            estudianteActual.FechaNacimiento = estudiante.FechaNacimiento;
            estudianteActual.Genero = estudiante.Genero;
            estudianteActual.Turno = estudiante.Turno;
            estudianteActual.TipoIngreso = estudiante.TipoIngreso;
            estudianteActual.EstaBecado = estudiante.EstaBecado;
            estudianteActual.PorcentajeBeca = estudiante.PorcentajeBeca;
            estudianteActual.TerminoCondicione = estudiante.TerminoCondicione;

            var rowCounts = _context.SaveChanges();

            if (rowCounts > 0)
            {
                ViewBag.Mensaje = "Estudiante modificado correctamente!";
            }
            else
            {
                ViewBag.Mensaje = "Algo salió mal al modificar el estudiante.";
            }

            return RedirectToAction("Lista");
        }



        [HttpGet]
        public IActionResult Eliminar(string matricula)
        {
            var estudiante = _context.Estudiantes.FirstOrDefault(e => e.Matricula == matricula);
            if (estudiante == null)
            {
                ViewBag.Mensaje = "El estudiante no existe.";
                return RedirectToAction("Lista");
            }

            _context.Estudiantes.Remove(estudiante);
            var rowCounts = _context.SaveChanges();
            if (rowCounts > 0)
            {
                ViewBag.Mensaje = "Estudiante eliminado correctamente!";
            }
            else
            {
                ViewBag.Mensaje = "Algo salio mal al eliminar el estudiante";

            }
            return RedirectToAction("Lista");
        }
    }
}

Actividad4LenPro3/Views/Estudiantes/Crear.cshtml
@{
    ViewData["Title"] = "Crear Estudiante";
}
@model Actividad4LenPro3.Models.Estudiante;

<h2>@ViewData["Title"]</h2>

<form asp-action="Registrar" method="post">
    <div class="form-group mb-2">
        <label asp-for="NombreCompleto"></label>
        <input asp-for="NombreCompleto" class="form-control" placeholder="Escribe tu nombre completo" />
        <span asp-validation-for="NombreCompleto" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Matricula"></label>
        <input asp-for="Matricula" class="form-control" placeholder="AB-0000-00000" />
        <span asp-validation-for="Matricula" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Carrera"></label>
        <select asp-for="Carrera" class="form-control">
            <option value="">Seleccione...</option>
            <option value="Ing.Software">Ing. Software</option>
            <option value="Ing.Electrica">Ing. Eléctrica</option>
            <option value="Ing.Industrial">Ing. Industrial</option>
            <option value="Enfermeria">Enfermería</option>
            <option value="Otro">Otro</option>
        </select>
        <span asp-validation-for="Carrera" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="CorreoElectronico"></label>
        <input asp-for="CorreoElectronico" class="form-control" placeholder="example@instituto.edu" />
        <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Telefono"></label>
        <input asp-for="Telefono" class="form-control" placeholder="000-000-0000" />
        <span asp-validation-for="Telefono" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="FechaNacimiento"></label>
        <input asp-for="FechaNacimiento" class="form-control" type="date" />
        <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Genero"></label>
        <select asp-for="Genero" class="form-control">
            <option value="">Seleccione...</option>
            <option value="Masculino">Masculino</option>
            <option value="Femenino">Femenino</option>
            <option value="Otro">Otro</option>
        </select>
        <span asp-validation-for="Genero" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Turno"></label>
        <select asp-for="Turno" class="form-control">
            <option value="">Seleccione...</option>
            <option value="Mañana">Mañana</option>
            <option value="Tarde">Tarde</option>
            <option value="Noche">Noche</option>
        </select>
        <span asp-validation-for="Turno" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="TipoIngreso"></label>
        <select asp-for="TipoIngreso" class="form-control">
            <option value="">Seleccione...</option>
            <option value="Nuevo">Nuevo</option>
            <option value="Readmitido">Readmitido</option>
            <option value="Otro">Otro</option>
        </select>
        <span asp-validation-for="TipoIngreso" class="text-danger"></span>
    </div>

    <div class="form-group mb-2 form-check">
        <input asp-for="EstaBecado" class="form-check-input" />
        <label class="form-check-label" asp-for="EstaBecado"></label>
        <span asp-validation-for="EstaBecado" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="PorcentajeBeca"></label>
        <input asp-for="PorcentajeBeca" class="form-control-range" type="range" min="0" max="10"/>
        <span asp-validation-for="PorcentajeBeca" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="TerminoCondicione"></label>
        <select asp-for="TerminoCondicione" class="form-control">
            <option value="">Seleccione...</option>
            <option value="True">Sí</option>
            <option value="False">No</option>
        </select>
        <span asp-validation-for="TerminoCondicione" class="text-danger"></span>
    </div>
       
    <div class="d-flex align-items-center gap-2">
        <button type="submit" class="btn btn-primary my-2">Guardar</button>
        <a type="button" asp-action="Lista" class="btn btn-secondary my-2">Atras</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Actividad4LenPro3/Views/Estudiantes/Editar.cshtml
@{
    ViewBag.Title = "Editar Estudiante";
}

@model Actividad4LenPro3.Models.Estudiante
<h2>@ViewBag.Title</h2>

@if(ViewBag.Message != null)
{
    <div class="alert alert-danger">
        @ViewBag.Message
    </div>
}
else 
{
    <form asp-action="Editar" method="post">
        <div class="form-group mb-2">
            <label asp-for="NombreCompleto"></label>
            <input asp-for="NombreCompleto" class="form-control" placeholder="Escribe tu nombre completo" />
            <span asp-validation-for="NombreCompleto" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="Matricula"></label>
            <input readonly="true" asp-for="Matricula" class="form-control" placeholder="AB-0000-00000" />
            <span asp-validation-for="Matricula" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="Carrera"></label>
            <select asp-for="Carrera" class="form-control">
                <option value="">Seleccione...</option>
                <asp-items value="Ing.Software">Ing. Software</asp-items>
                <asp-items value="Ing.Electrica">Ing. Eléctrica</asp-items>
                <option value="Ing.Industrial">Ing. Industrial</option>
                <option value="Enfermeria">Enfermería</option>
                <option value="Otro">Otro</option>
            </select>
            <span asp-validation-for="Carrera" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="CorreoElectronico"></label>
            <input asp-for="CorreoElectronico" class="form-control" placeholder="example@instituto.edu" />
            <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="Telefono"></label>
            <input asp-for="Telefono" class="form-control" placeholder="000-000-0000" />
            <span asp-validation-for="Telefono" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="FechaNacimiento"></label>
            <input asp-for="FechaNacimiento" class="form-control" type="date" />
            <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="Genero"></label>
            <select asp-for="Genero" class="form-control">
                <option value="">Seleccione...</option>
                <option value="Masculino">Masculino</option>
                <option value="Femenino">Femenino</option>
                <option value="Otro">Otro</option>
            </select>
            <span asp-validation-for="Genero" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="Turno"></label>
            <select asp-for="Turno" class="form-control">
                <option value="">Seleccione...</option>
                <option value="Mañana">Mañana</option>
                <option value="Tarde">Tarde</option>
                <option value="Noche">Noche</option>
            </select>
            <span asp-validation-for="Turno" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="TipoIngreso"></label>
            <select asp-for="TipoIngreso" class="form-control">
                <option value="">Seleccione...</option>
                <option value="Nuevo">Nuevo</option>
                <option value="Readmitido">Readmitido</option>
                <option value="Otro">Otro</option>
            </select>
            <span asp-validation-for="TipoIngreso" class="text-danger"></span>
        </div>

        <div class="form-group mb-2 form-check">
            <input asp-for="EstaBecado" class="form-check-input" />
            <label class="form-check-label" asp-for="EstaBecado"></label>
            <span asp-validation-for="EstaBecado" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="PorcentajeBeca"></label>
            <input asp-for="PorcentajeBeca" class="form-control-range" type="range" min="0" max="10"/>
            <span asp-validation-for="PorcentajeBeca" class="text-danger"></span>
        </div>

        <div class="form-group mb-2">
            <label asp-for="TerminoCondicione"></label>
            <select asp-for="TerminoCondicione" class="form-control">
                <option value="">Seleccione...</option>
                <option value="True">Sí</option>
                <option value="False">No</option>
            </select>
            <span asp-validation-for="TerminoCondicione" class="text-danger"></span>
        </div>

        <div class="d-flex align-items-center gap-2">
            <button type="submit" class="btn btn-primary my-2">Guardar</button>
            <a type="button" asp-action="Lista" class="btn btn-secondary my-2">Atras</a>
        </div>
    </form>
}


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Actividad4LenPro3/Views/Estudiantes/Lista.cshtml
@{
    ViewData["Title"] = "Lista de Estudiantes";
}
@model IEnumerable<Actividad4LenPro3.Models.Estudiante>


<h2>@ViewData["Title"]</h2>

@if (Model != null && Model.Any())
{
    <div class="alert alert-success">
        Se encontraron @Model.Count() estudiantes.
    </div>
}
else
{
    <div class="alert alert-warning">
        No se encontraron estudiantes registrados.
    </div>
}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre Completo</th>
            <th>Matrícula</th>
            <th>Carrera</th>
            <th>Correo Electrónico</th>
            <th>Teléfono</th>
            <th>Fecha de Nacimiento</th>
            <th>Género</th>
            <th>Turno</th>
            <th>Tipo Ingreso</th>
            <th>Esta Becado</th>
            <th>Porcentaje Beca</th>
            <th>Termino Condiciones</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var estudiante in Model)
        {
            <tr>
                <td>@estudiante.NombreCompleto</td>
                <td>@estudiante.Matricula</td>
                <td>@estudiante.Carrera</td>
                <td>@estudiante.CorreoElectronico</td>
                <td>@estudiante.Telefono</td>
                <td>@estudiante.FechaNacimiento.ToString("dd/MM/yyyy")</td>
                <td>@estudiante.Genero</td>
                <td>@estudiante.Turno</td>
                <td>@estudiante.TipoIngreso</td>
                <td>@estudiante.EstaBecado</td>
                <td>@estudiante.PorcentajeBeca</td>
                <td>@estudiante.TerminoCondicione</td>
                <td>
                    <div class="d-flex align-items-center gap-2">
                        <a asp-action="Editar" asp-controller="Estudiantes" asp-route-matricula="@estudiante.Matricula" class="btn btn-success me-2">Editar</a>
                        <a asp-action="Eliminar" asp-controller="Estudiantes" asp-route-matricula="@estudiante.Matricula" class="btn btn-danger">Eliminar</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" asp-controller="Estudiantes" asp-action="Index">Registrar</a>