Actividad4LenPro3/Models/Materia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Actividad4LenPro3.Models;

public partial class Materia
{
    [Key]
    public int Id { get; set; }
    [Required(ErrorMessage ="El nombre es requerido")]
    public string Nombre { get; set; } = null!;
    [Required(ErrorMessage = "El codigo es requerido")]
    public string Codigo { get; set; } = null!;
    [Required(ErrorMessage ="Los creditos son requeridos")]
    [Range(0, 10, ErrorMessage ="Los creditos deben estar entre 0 y 10")]
    public int Creditos { get; set; }
    [Required(ErrorMessage ="La carrera es requerida")]
    public string Carrera { get; set; } = null!;

    public virtual ICollection<Calificacione> Calificaciones { get; set; } = new List<Calificacione>();
}

Actividad4LenPro3/Controllers/MateriasController.cs
using Actividad4LenPro3.Models;
using Microsoft.AspNetCore.Mvc;

namespace Actividad4LenPro3.Controllers
{
    public class MateriasController : Controller
    {
        private readonly Actividad4LenPro3Context _context;

        public MateriasController(Actividad4LenPro3Context context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View("Crear");
        }


        [HttpPost]
        public IActionResult Registrar(Materia model)
        {
            if (!ModelState.IsValid)
            {
                return View("Crear", model);
            }

            _context.Materias.Add(model);
            var rowCounts = _context.SaveChanges();

            if (rowCounts > 0)
            {
                ViewBag.Mensaje = "Materia registrada correctamente!";
            }
            else
            {
                ViewBag.Mensaje = "Algo salio mal al registrar la materia";

            }

            return RedirectToAction("Lista");
        }


        [HttpGet]
        public IActionResult Lista()
        {
            var materias = _context.Materias.ToList();
            return View(materias);
        }


        [HttpGet]
        public IActionResult Editar(int id)
        {
            var materia = _context.Materias.FirstOrDefault(e => e.Id == id);

            if (materia == null)
            {
                ViewBag.Mensaje = "La materia no existe.";
                return RedirectToAction("Lista");
            }

            return View("Editar", materia);
        }



        [HttpPost]
        public IActionResult Editar(Materia materia)
        {
            if (!ModelState.IsValid)
            {
                return View("Editar", materia);
            }

            var materiaActual = _context.Materias.FirstOrDefault(e => e.Id == materia.Id);

            if (materiaActual == null)
            {
                ViewBag.Mensaje = "La materia no existe.";
                return RedirectToAction("Lista");
            }


            materiaActual.Nombre = materia.Nombre;
            materiaActual.Creditos = materia.Creditos;
            materiaActual.Carrera = materia.Carrera;

            var rowCounts = _context.SaveChanges();

            if (rowCounts > 0)
            {
                ViewBag.Mensaje = "¡Materia modificada correctamente!";
            }
            else
            {
                ViewBag.Mensaje = "No se realizaron cambios en la materia.";
            }

            return RedirectToAction("Lista");
        }




        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            var materia = _context.Materias.FirstOrDefault(e => e.Id == id);
            if (materia == null)
            {
                ViewBag.Mensaje = "La materia no existe.";
                return RedirectToAction("Lista");
            }

            _context.Materias.Remove(materia);
            var rowCounts = _context.SaveChanges();
            if (rowCounts > 0)
            {
                ViewBag.Mensaje = "Materia eliminado correctamente!";
            }
            else
            {
                ViewBag.Mensaje = "Algo salio mal al eliminar el materia";

            }
            return RedirectToAction("Lista");
        }
    }
}

Actividad4LenPro3/Views/Materias/Crear.cshtml
@{
    ViewData["Title"] = "Registrar Materia";
}
@model Actividad4LenPro3.Models.Materia;

<h2>@ViewData["Title"]</h2>

<form asp-action="Registrar" method="post">
    <div class="form-group mb-2">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control" placeholder="Nombre de la materia" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Codigo"></label>
        <input asp-for="Codigo" class="form-control" placeholder="AB-0000-00000" />
        <span asp-validation-for="Codigo" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Creditos"></label>
        <input asp-for="Creditos" type="number" class="form-control" placeholder="0 al 10" />
        <span asp-validation-for="Creditos" class="text-danger"></span>
    </div>


    <div class="form-group mb-2">
        <label asp-for="Carrera"></label>
        <select asp-for="Carrera" class="form-control">
            <option value="">Seleccione...</option>
            <option value="Ing.Software">Ing. Software</option>
            <option value="Ing.Electrica">Ing. Eléctrica</option>
            <option value="Ing.Industrial">Ing. Industrial</option>
            <option value="Enfermeria">Enfermería</option>
            <option value="Otro">Otro</option>
        </select>
        <span asp-validation-for="Carrera" class="text-danger"></span>
    </div>

       
    <div class="d-flex align-items-center gap-2">
        <button type="submit" class="btn btn-primary my-2">Guardar</button>
        <a type="button" asp-action="Lista" class="btn btn-secondary my-2">Atras</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Actividad4LenPro3/Views/Materias/Editar.cshtml
@{
    ViewData["Title"] = "Editar Materia";
}
@model Actividad4LenPro3.Models.Materia;

<h2>@ViewData["Title"]</h2>

<form asp-action="Editar" method="post">
    <div class="form-group mb-2">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control" placeholder="Nombre de la materia" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Codigo"></label>
        <input asp-for="Codigo" readonly class="form-control" placeholder="AB-0000-00000" />
        <span asp-validation-for="Codigo" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Creditos"></label>
        <input asp-for="Creditos" type="number" class="form-control" placeholder="0 al 10" />
        <span asp-validation-for="Creditos" class="text-danger"></span>
    </div>


    <div class="form-group mb-2">
        <label asp-for="Carrera"></label>
        <select asp-for="Carrera" class="form-control">
            <option value="">Seleccione...</option>
            <option value="Ing.Software">Ing. Software</option>
            <option value="Ing.Electrica">Ing. Eléctrica</option>
            <option value="Ing.Industrial">Ing. Industrial</option>
            <option value="Enfermeria">Enfermería</option>
            <option value="Otro">Otro</option>
        </select>
        <span asp-validation-for="Carrera" class="text-danger"></span>
    </div>


    <div class="d-flex align-items-center gap-2">
        <button type="submit" class="btn btn-primary my-2">Guardar</button>
        <a type="button" asp-action="Lista" class="btn btn-secondary my-2">Atras</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Actividad4LenPro3/Views/Materias/Lista.cshtml
@{
    ViewData["Title"] = "Lista de Materias";
}
@model IEnumerable<Actividad4LenPro3.Models.Materia>


<h2>@ViewData["Title"]</h2>

@if (Model != null && Model.Any())
{
    <div class="alert alert-success">
        Se encontraron @Model.Count() materias.
    </div>
}
else
{
    <div class="alert alert-warning">
        No se encontraron materias registrados.
    </div>
}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Codigo</th>
            <th>Creditos</th>
            <th>Carrera</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var materia in Model)
        {
            <tr>
                <td>@materia.Nombre</td>
                <td>@materia.Codigo</td>
                <td>@materia.Creditos</td>
                <td>@materia.Carrera</td>
                <td>
                    <div class="d-flex align-items-center gap-2">
                        <a asp-action="Editar" asp-controller="Materias" asp-route-id="@materia.Id" class="btn btn-success me-2">Editar</a>
                        <a asp-action="Eliminar" asp-controller="Materias" asp-route-id="@materia.Id" class="btn btn-danger">Eliminar</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" asp-controller="Materias" asp-action="Index">Registrar</a>