Actividad4LenPro3/Models/Calificacione.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Actividad4LenPro3.Models;

public partial class Calificacione
{
    [Key]
    public int Id { get; set; }
    [Required(ErrorMessage ="La matricula del estudiante es requerida")]
    public string MatriculaEstudiante { get; set; } = null!;
    [Required(ErrorMessage ="El codigo de la materia es requerido")]
    public string CodigoMateria { get; set; } = null!;
    [Required(ErrorMessage ="La nota es requerida")]
    [Range(0, 100, ErrorMessage ="La calificacion debe ser entre 0 y 100")]
    public double Nota { get; set; }
    [Required(ErrorMessage ="El periodo es requerido")]
    public string Periodo { get; set; } = null!;

    [ValidateNever]
    public virtual Materia CodigoMateriaNavigation { get; set; } = null!;
    [ValidateNever]
    public virtual Estudiante MatriculaEstudianteNavigation { get; set; } = null!;
}

Actividad4LenPro3/Controllers/CalificacionesController.cs
using Actividad4LenPro3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Actividad4LenPro3.Controllers
{
    public class CalificacionesController : Controller
    {
        private readonly Actividad4LenPro3Context _context;

        public CalificacionesController(Actividad4LenPro3Context context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Estudiantes = _context.Estudiantes
                .Select(e => new SelectListItem
                {
                    Value = e.Matricula,
                    Text = e.Matricula + " - " + e.NombreCompleto
                }).ToList();

            ViewBag.Materias = _context.Materias
                .Select(m => new SelectListItem
                {
                    Value = m.Codigo,
                    Text = m.Codigo + " - " + m.Nombre
                }).ToList();

            return View("Crear");
        }


        [HttpPost]
        public IActionResult Registrar(Calificacione model)
        {
            if (!ModelState.IsValid)
            {

                ViewBag.Estudiantes = _context.Estudiantes
                    .Select(e => new SelectListItem
                    {
                        Value = e.Matricula,
                        Text = e.Matricula + " - " + e.NombreCompleto
                    }).ToList();

                ViewBag.Materias = _context.Materias
                    .Select(m => new SelectListItem
                    {
                        Value = m.Codigo,
                        Text = m.Codigo + " - " + m.Nombre
                    }).ToList();

                return View("Crear", model);
            }

            _context.Calificaciones.Add(model);
            _context.SaveChanges();

            TempData["Mensaje"] = "¡Calificación registrada correctamente!";
            return RedirectToAction("Lista");
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var calificacion = _context.Calificaciones.FirstOrDefault(e => e.Id == id);

            if (calificacion == null)
            {
                ViewBag.Mensaje = "La calificacion no existe.";
                return RedirectToAction("Lista");
            }

            ViewBag.Estudiantes = _context.Estudiantes
                   .Select(e => new SelectListItem
                   {
                       Value = e.Matricula,
                       Text = e.Matricula + " - " + e.NombreCompleto
                   }).ToList();

            ViewBag.Materias = _context.Materias
                .Select(m => new SelectListItem
                {
                    Value = m.Codigo,
                    Text = m.Codigo + " - " + m.Nombre
                }).ToList();
            return View("Editar", calificacion);
        }


        [HttpPost]
        public IActionResult Editar(Calificacione calificacion)
        {
            if (!ModelState.IsValid)
            {
                return View("Editar", calificacion);
            }

            var calificacionActual = _context.Calificaciones.FirstOrDefault(e => e.Id == calificacion.Id);

            if (calificacionActual == null)
            {
                ViewBag.Mensaje = "La materia no existe.";
                return RedirectToAction("Lista");
            }


            calificacionActual.MatriculaEstudiante = calificacion.MatriculaEstudiante;
            calificacionActual.CodigoMateria = calificacion.CodigoMateria;
            calificacionActual.Nota = calificacion.Nota;
            calificacionActual.Periodo = calificacion.Periodo;

            var rowCounts = _context.SaveChanges();

            if (rowCounts > 0)
            {
                ViewBag.Mensaje = "¡Calificaion modificada correctamente!";
            }
            else
            {
                ViewBag.Mensaje = "No se realizaron cambios en la calificacion.";
            }

            return RedirectToAction("Lista");
        }


        [HttpGet]
        public IActionResult Lista()
        {
            var calificaciones = _context.Calificaciones.ToList();
            return View(calificaciones);
        }

        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            var calificacion = _context.Calificaciones.FirstOrDefault(c => c.Id == id);
            if (calificacion == null)
            {
                TempData["Mensaje"] = "La calificación no existe.";
                return RedirectToAction("Lista");
            }

            _context.Calificaciones.Remove(calificacion);
            _context.SaveChanges();

            TempData["Mensaje"] = "Calificación eliminada correctamente.";
            return RedirectToAction("Lista");
        }
    }
}

Actividad4LenPro3/Views/Calificaciones/Crear.cshtml
@model Actividad4LenPro3.Models.Calificacione

@{
    ViewData["Title"] = "Registrar Calificación";
}

<h2>Registrar Calificación</h2>

<form asp-action="Registrar" method="post">
    <div class="form-group">
        <label asp-for="MatriculaEstudiante"></label>
        <select asp-for="MatriculaEstudiante" asp-items="ViewBag.Estudiantes" class="form-control">
            <option value="">Seleccione un estudiante</option>
        </select>
        <span asp-validation-for="MatriculaEstudiante" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CodigoMateria"></label>
        <select asp-for="CodigoMateria" asp-items="ViewBag.Materias" class="form-control">
            <option value="">Seleccione una materia</option>
        </select>
        <span asp-validation-for="CodigoMateria" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Nota"></label>
        <input asp-for="Nota" class="form-control" />
        <span asp-validation-for="Nota" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Periodo"></label>
        <input asp-for="Periodo" class="form-control" />
        <span asp-validation-for="Periodo" class="text-danger"></span>
    </div>

    <div class="d-flex align-items-center gap-2">
        <button type="submit" class="btn btn-primary my-2">Guardar</button>
        <a type="button" asp-action="Lista" class="btn btn-secondary my-2">Atras</a>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Actividad4LenPro3/Views/Calificaciones/Editar.cshtml
@model Actividad4LenPro3.Models.Calificacione

@{
    ViewData["Title"] = "Editar Calificación";
}

<h2>Editar Calificación</h2>

<form asp-action="Editar" method="post">
    <div class="form-group">
        <label asp-for="MatriculaEstudiante"></label>
        <select asp-for="MatriculaEstudiante" asp-items="ViewBag.Estudiantes" class="form-control">
            <option value="">Seleccione un estudiante</option>
        </select>
        <span asp-validation-for="MatriculaEstudiante" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CodigoMateria"></label>
        <select asp-for="CodigoMateria" asp-items="ViewBag.Materias" class="form-control">
            <option value="">Seleccione una materia</option>
        </select>
        <span asp-validation-for="CodigoMateria" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Nota"></label>
        <input asp-for="Nota" class="form-control" />
        <span asp-validation-for="Nota" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Periodo"></label>
        <input asp-for="Periodo" class="form-control" />
        <span asp-validation-for="Periodo" class="text-danger"></span>
    </div>

    <div class="d-flex align-items-center gap-2">
        <button type="submit" class="btn btn-primary my-2">Guardar</button>
        <a type="button" asp-action="Lista" class="btn btn-secondary my-2">Atras</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Actividad4LenPro3/Views/Calificaciones/Lista.cshtml
@{
    ViewData["Title"] = "Lista de Calificaciones";
}
@model IEnumerable<Actividad4LenPro3.Models.Calificacione>


<h2>@ViewData["Title"]</h2>

@if (Model != null && Model.Any())
{
    <div class="alert alert-success">
        Se encontraron @Model.Count() calificaciones.
    </div>
}
else
{
    <div class="alert alert-warning">
        No se encontraron calificaciones registrados.
    </div>
}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Matricula Estudiante</th>
            <th>Codigo Materia</th>
            <th>Nota</th>
            <th>Periodo</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var materia in Model)
        {
            <tr>
                <td>@materia.MatriculaEstudiante</td>
                <td>@materia.CodigoMateria</td>
                <td>@materia.Nota</td>
                <td>@materia.Periodo</td>
                <td>
                    <div class="d-flex align-items-center gap-2">
                        <a asp-action="Editar" asp-controller="Calificaciones" asp-route-id="@materia.Id" class="btn btn-success me-2">Editar</a>
                        <a asp-action="Eliminar" asp-controller="Calificaciones" asp-route-id="@materia.Id" class="btn btn-danger">Eliminar</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" asp-controller="Calificaciones" asp-action="Index">Registrar</a>